/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useControls, folder } from 'leva'

import { useStencil } from './utils/stencilBuffer'
import { SEASONS } from './store/useSceneState'

const BASE_Y = 0.512

export function Boat({ store, ...props }) {
    const stencil = useStencil(SEASONS.spring)

    const meshRef = useRef(null)
    const shadowMeshRef = useRef(null)

    const controls = useControls(
        {
            Boat: folder({
                bobAmplitude: { value: 0.005, min: 0, max: 0.05, step: 0.001 },
                bobSpeed: { value: 1.0, min: 0, max: 3, step: 0.1 },
                pitchAmplitude: { value: 0.04, min: 0, max: 0.3, step: 0.005 },
                pitchSpeed: { value: 0.8, min: 0, max: 3, step: 0.1 },
                rollAmplitude: { value: 0.02, min: 0, max: 0.3, step: 0.005 },
                rollSpeed: { value: 0.6, min: 0, max: 3, step: 0.1 },
            }),
        },
        { store }
    )

    const { nodes } = useGLTF('./models/Boat/boatMerged.glb')
    const bakedTexture = useTexture('./models/Boat/baked_cleaned.png')

    // eslint-disable-next-line
    bakedTexture.flipY = false

    useFrame((state) => {
        const elapsedTime = state.clock.elapsedTime

        meshRef.current.position.y =
            BASE_Y +
            Math.sin(elapsedTime * controls.bobSpeed) * controls.bobAmplitude
        meshRef.current.rotation.x =
            Math.sin(elapsedTime * controls.pitchSpeed) *
            controls.pitchAmplitude
        meshRef.current.rotation.z =
            Math.sin(elapsedTime * controls.rollSpeed + 1.0) *
            controls.rollAmplitude

        shadowMeshRef.current.position.y =
            BASE_Y +
            0.001 +
            Math.sin(elapsedTime * controls.bobSpeed) * controls.bobAmplitude
        shadowMeshRef.current.rotation.x =
            Math.sin(elapsedTime * controls.pitchSpeed) *
            controls.pitchAmplitude
        shadowMeshRef.current.rotation.z =
            Math.sin(elapsedTime * controls.rollSpeed + 1.0) *
            controls.rollAmplitude
    })

    return (
        <group dispose={null} {...props}>
            <mesh
                ref={meshRef}
                geometry={nodes.boat.geometry}
                position={[0.068, BASE_Y, 0.603]}
            >
                <meshBasicMaterial map={bakedTexture} {...stencil} />
            </mesh>
            <mesh
                ref={shadowMeshRef}
                geometry={nodes.boat.geometry}
                position={[0.068, BASE_Y + 0.001, 0.603]}
                receiveShadow
            >
                <shadowMaterial transparent opacity={0.35} {...stencil} />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/Boat/boatMerged.glb')
useTexture.preload('./models/Boat/baked_cleaned.png')
