/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF, useTexture } from '@react-three/drei'

export function BottleLabel(props) {
    const { nodes } = useGLTF('./models/Label/Label.glb')
    const bakedTexture = useTexture('./models/Label/bakedWithText.jpg')

    // eslint-disable-next-line
    bakedTexture.flipY = false

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.BottleLabel.geometry}
                position={[0, 2.043, 0.914]}
            >
                <meshBasicMaterial map={bakedTexture} />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/Label/Label.glb')
useTexture.preload('./models/Label/bakedWithText.jpg')
