/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useTexture } from '@react-three/drei'

export function CorkModel({
    onPointerOver,
    onPointerOut,
    onPointerDown,
    onPointerUp,
    onClick,
    color,
}) {
    const { nodes } = useGLTF('./models/Cork/Cork.glb')
    const bakedTexture = useTexture('./models/Cork/baked.jpg')

    // eslint-disable-next-line
    bakedTexture.flipY = false

    return (
        <group
            onPointerOver={onPointerOver}
            onPointerOut={onPointerOut}
            onPointerDown={onPointerDown}
            onPointerUp={onPointerUp}
            onClick={onClick}
            dispose={null}
        >
            <mesh
                geometry={nodes.Cork.geometry}
                position={[-0.023, 2.426, 0.011]}
            >
                <meshBasicMaterial map={bakedTexture} color={color} />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/Cork/Cork.glb')
useTexture.preload('./models/Cork/baked.jpg')
