/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF, useTexture } from '@react-three/drei'

export function Rope(props) {
    const { nodes } = useGLTF('./models/Rope/RopeAndRing.glb')
    const bakedRopeTexture = useTexture('./models/Rope/baked_compressed.jpg')

    const ringMatcap = useTexture('./textures/bronzeMatcap/matcap.png')

    // eslint-disable-next-line
    bakedRopeTexture.flipY = false

    return (
        <group {...props} dispose={null}>
            <mesh
                name="merged002"
                geometry={nodes.merged002.geometry}
                position={[-0.025, 2.293, 0.008]}
            >
                <meshBasicMaterial map={bakedRopeTexture} />
            </mesh>
            <mesh
                name="Ring002"
                geometry={nodes.Ring002.geometry}
                position={[0.009, 2.246, 0.495]}
            >
                <meshMatcapMaterial matcap={ringMatcap} />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/Rope/RopeAndRing.glb')
useTexture.preload('./models/Rope/baked_compressed.jpg')
useTexture.preload('./textures/bronzeMatcap/matcap.png')
